State.Example/Models/MyTestFilterAttribute.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ViewbagExample.Models
{
    public class MyTestFilterAttribute : ActionFilterAttribute
    {
        public override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            Debug.WriteLine("Before calling");
        }

        public override void OnActionExecuted(ActionExecutedContext filterContext)
        {
            Debug.WriteLine("After calling");
        }
    }
}

State.Example/Controllers/SampleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ViewbagExample.Models;

namespace ViewbagExample.Controllers
{
    public class SampleController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.MyCurrentDate = DateTime.Now.ToString();
            return View("Index");
        }

        [MyTestFilter]
        public ActionResult Page1()
        {
            return View();
        }

        public ActionResult Page2()
        {
            return View();
        }

        public ActionResult SamplePartial()
        {
            ViewBag.Data = DateTime.Now.ToString();
            return PartialView("_MyDateTime");
        }
    }
}

State.Example/Views/Sample/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        Current Date = @ViewData["MyCurrentDate"]
    </div>
</body>
</html>

State.Example/Views/Sample/Page1.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Page1</title>
</head>
<body>
    <div>
        @Html.Partial("_Login")
        <br />
        @Html.Partial("_Login")
        <br />
        @Html.Action("SamplePartial", "Sample")
    </div>
</body>
</html>

State.Example/Views/Sample/Page2.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Page2</title>
</head>
<body>
    <div>
        @Html.Partial("_Login")
        <hr />
        @Html.Action("SamplePartial", "Sample")
    </div>
</body>
</html>

State.Example/Views/Shared/_Login.cshtml
<h1>This is the user control</h1>
<br />
<label>Login Control</label>
<br />
<input type="text" />
<br />
<input type="password" />
<br />
<input type="submit" />

State.Example/Views/Shared/_MyDateTime.cshtml
DateTime = @ViewBag.Data